// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: memiavl/changelog.proto

package proto

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	iavl "github.com/cosmos/iavl"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NamedChangeSet combine a tree name with the changeset
type NamedChangeSet struct {
	Changeset            iavl.ChangeSet `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NamedChangeSet) Reset()         { *m = NamedChangeSet{} }
func (m *NamedChangeSet) String() string { return proto.CompactTextString(m) }
func (*NamedChangeSet) ProtoMessage()    {}
func (*NamedChangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ab2c074e463b59, []int{0}
}
func (m *NamedChangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedChangeSet.Unmarshal(m, b)
}
func (m *NamedChangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedChangeSet.Marshal(b, m, deterministic)
}
func (m *NamedChangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedChangeSet.Merge(m, src)
}
func (m *NamedChangeSet) XXX_Size() int {
	return xxx_messageInfo_NamedChangeSet.Size(m)
}
func (m *NamedChangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedChangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_NamedChangeSet proto.InternalMessageInfo

func (m *NamedChangeSet) GetChangeset() iavl.ChangeSet {
	if m != nil {
		return m.Changeset
	}
	return iavl.ChangeSet{}
}

func (m *NamedChangeSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// TreeNameUpgrade defines upgrade of tree names:
// - New tree: { name: "tree" }
// - Delete tree: { name: "tree", delete: true }
// - Rename tree: { name: "new-tree", rename_from: "old-tree" }
type TreeNameUpgrade struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RenameFrom           string   `protobuf:"bytes,2,opt,name=rename_from,json=renameFrom,proto3" json:"rename_from,omitempty"`
	Delete               bool     `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreeNameUpgrade) Reset()         { *m = TreeNameUpgrade{} }
func (m *TreeNameUpgrade) String() string { return proto.CompactTextString(m) }
func (*TreeNameUpgrade) ProtoMessage()    {}
func (*TreeNameUpgrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ab2c074e463b59, []int{1}
}
func (m *TreeNameUpgrade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeNameUpgrade.Unmarshal(m, b)
}
func (m *TreeNameUpgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeNameUpgrade.Marshal(b, m, deterministic)
}
func (m *TreeNameUpgrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeNameUpgrade.Merge(m, src)
}
func (m *TreeNameUpgrade) XXX_Size() int {
	return xxx_messageInfo_TreeNameUpgrade.Size(m)
}
func (m *TreeNameUpgrade) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeNameUpgrade.DiscardUnknown(m)
}

var xxx_messageInfo_TreeNameUpgrade proto.InternalMessageInfo

func (m *TreeNameUpgrade) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TreeNameUpgrade) GetRenameFrom() string {
	if m != nil {
		return m.RenameFrom
	}
	return ""
}

func (m *TreeNameUpgrade) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

// MultiTreeMetadata stores the metadata for MultiTree
type MultiTreeMetadata struct {
	CommitInfo           *CommitInfo `protobuf:"bytes,1,opt,name=commit_info,json=commitInfo,proto3" json:"commit_info,omitempty"`
	InitialVersion       int64       `protobuf:"varint,2,opt,name=initial_version,json=initialVersion,proto3" json:"initial_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MultiTreeMetadata) Reset()         { *m = MultiTreeMetadata{} }
func (m *MultiTreeMetadata) String() string { return proto.CompactTextString(m) }
func (*MultiTreeMetadata) ProtoMessage()    {}
func (*MultiTreeMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ab2c074e463b59, []int{2}
}
func (m *MultiTreeMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiTreeMetadata.Unmarshal(m, b)
}
func (m *MultiTreeMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiTreeMetadata.Marshal(b, m, deterministic)
}
func (m *MultiTreeMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiTreeMetadata.Merge(m, src)
}
func (m *MultiTreeMetadata) XXX_Size() int {
	return xxx_messageInfo_MultiTreeMetadata.Size(m)
}
func (m *MultiTreeMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiTreeMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_MultiTreeMetadata proto.InternalMessageInfo

func (m *MultiTreeMetadata) GetCommitInfo() *CommitInfo {
	if m != nil {
		return m.CommitInfo
	}
	return nil
}

func (m *MultiTreeMetadata) GetInitialVersion() int64 {
	if m != nil {
		return m.InitialVersion
	}
	return 0
}

// ChangelogEntry is a single entry in the changelog
type ChangelogEntry struct {
	Version              int64              `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Changesets           []*NamedChangeSet  `protobuf:"bytes,2,rep,name=changesets,proto3" json:"changesets,omitempty"`
	Upgrades             []*TreeNameUpgrade `protobuf:"bytes,3,rep,name=upgrades,proto3" json:"upgrades,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChangelogEntry) Reset()         { *m = ChangelogEntry{} }
func (m *ChangelogEntry) String() string { return proto.CompactTextString(m) }
func (*ChangelogEntry) ProtoMessage()    {}
func (*ChangelogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ab2c074e463b59, []int{3}
}
func (m *ChangelogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangelogEntry.Unmarshal(m, b)
}
func (m *ChangelogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangelogEntry.Marshal(b, m, deterministic)
}
func (m *ChangelogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangelogEntry.Merge(m, src)
}
func (m *ChangelogEntry) XXX_Size() int {
	return xxx_messageInfo_ChangelogEntry.Size(m)
}
func (m *ChangelogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangelogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ChangelogEntry proto.InternalMessageInfo

func (m *ChangelogEntry) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ChangelogEntry) GetChangesets() []*NamedChangeSet {
	if m != nil {
		return m.Changesets
	}
	return nil
}

func (m *ChangelogEntry) GetUpgrades() []*TreeNameUpgrade {
	if m != nil {
		return m.Upgrades
	}
	return nil
}

func init() {
	proto.RegisterType((*NamedChangeSet)(nil), "memiavl.NamedChangeSet")
	proto.RegisterType((*TreeNameUpgrade)(nil), "memiavl.TreeNameUpgrade")
	proto.RegisterType((*MultiTreeMetadata)(nil), "memiavl.MultiTreeMetadata")
	proto.RegisterType((*ChangelogEntry)(nil), "memiavl.ChangelogEntry")
}

func init() { proto.RegisterFile("memiavl/changelog.proto", fileDescriptor_39ab2c074e463b59) }

var fileDescriptor_39ab2c074e463b59 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcf, 0xaa, 0xda, 0x40,
	0x14, 0xc6, 0x1b, 0x23, 0xfe, 0x39, 0x01, 0xa5, 0x53, 0xa9, 0xa9, 0x1b, 0x43, 0x28, 0x6d, 0x36,
	0x4d, 0x40, 0x85, 0xee, 0x95, 0x16, 0xba, 0xb0, 0x8b, 0xf4, 0x0f, 0xb4, 0x8b, 0xca, 0x98, 0x1c,
	0xe3, 0x40, 0x26, 0x23, 0x93, 0x51, 0xe8, 0xa3, 0xf4, 0x8d, 0xfa, 0x14, 0xf7, 0x59, 0x2e, 0x99,
	0x8c, 0xa3, 0xf7, 0xae, 0x3c, 0xe7, 0x3b, 0xdf, 0xef, 0x78, 0xf2, 0x0d, 0x4c, 0x39, 0x72, 0x46,
	0x2f, 0x65, 0x92, 0x1d, 0x69, 0x55, 0x60, 0x29, 0x8a, 0xf8, 0x24, 0x85, 0x12, 0xa4, 0x6f, 0x06,
	0xb3, 0x49, 0x21, 0x0a, 0xa1, 0xb5, 0xa4, 0xa9, 0xda, 0xf1, 0x6c, 0x72, 0x07, 0xd5, 0xa8, 0x8c,
	0xfa, 0xc6, 0x6e, 0x13, 0x9c, 0x33, 0xb5, 0x63, 0xd5, 0xc1, 0x00, 0xe1, 0x2f, 0x18, 0x7d, 0xa5,
	0x1c, 0xf3, 0x8d, 0x46, 0xbe, 0xa1, 0x22, 0x4b, 0x18, 0x5a, 0xde, 0x77, 0x02, 0x27, 0xf2, 0x16,
	0xe3, 0xb8, 0xa1, 0x63, 0xeb, 0x59, 0x77, 0xff, 0x3f, 0xcc, 0x5f, 0xa4, 0x37, 0x1f, 0x21, 0xd0,
	0xad, 0x28, 0x47, 0xbf, 0x13, 0x38, 0xd1, 0x30, 0xd5, 0x75, 0xf8, 0x07, 0xc6, 0xdf, 0x25, 0x62,
	0xb3, 0xfe, 0xc7, 0xa9, 0x90, 0x34, 0x47, 0x6b, 0x73, 0x6e, 0x36, 0x32, 0x07, 0x4f, 0x62, 0x53,
	0xed, 0x0e, 0x52, 0x70, 0xb3, 0x01, 0x5a, 0xe9, 0xb3, 0x14, 0x9c, 0xbc, 0x86, 0x5e, 0x8e, 0x25,
	0x2a, 0xf4, 0xdd, 0xc0, 0x89, 0x06, 0xa9, 0xe9, 0x42, 0x09, 0x2f, 0xb7, 0xe7, 0x52, 0xb1, 0xe6,
	0x4f, 0xb6, 0xa8, 0x68, 0x4e, 0x15, 0x25, 0x2b, 0xf0, 0xee, 0x3e, 0xd2, 0xdc, 0xff, 0x2a, 0x36,
	0x01, 0xc4, 0x1b, 0x3d, 0xfb, 0x52, 0x1d, 0x44, 0x0a, 0x99, 0xad, 0xc9, 0x7b, 0x18, 0xb3, 0x8a,
	0x29, 0x46, 0xcb, 0xdd, 0x05, 0x65, 0xcd, 0x44, 0xa5, 0xef, 0x70, 0xd3, 0x91, 0x91, 0x7f, 0xb6,
	0x6a, 0xf8, 0xcf, 0x81, 0xd1, 0xe6, 0xfa, 0x24, 0x9f, 0x2a, 0x25, 0xff, 0x12, 0x1f, 0xfa, 0x57,
	0xc6, 0xd1, 0xcc, 0xb5, 0x25, 0x1f, 0x01, 0x6c, 0x42, 0xb5, 0xdf, 0x09, 0xdc, 0xc8, 0x5b, 0x4c,
	0xed, 0x29, 0x4f, 0x63, 0x4f, 0xef, 0xac, 0x64, 0x05, 0x83, 0x73, 0x9b, 0x58, 0xed, 0xbb, 0x1a,
	0xf3, 0x2d, 0xf6, 0x2c, 0xd2, 0xd4, 0x3a, 0xd7, 0xef, 0x7e, 0xbf, 0x2d, 0x98, 0x3a, 0x9e, 0xf7,
	0x71, 0x26, 0x78, 0x52, 0x23, 0xfb, 0xa0, 0x9f, 0x38, 0x13, 0xa5, 0x6e, 0xf2, 0x7d, 0xa2, 0xfb,
	0x7d, 0x4f, 0xff, 0x2c, 0x1f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x87, 0x34, 0x22, 0x64, 0x64, 0x02,
	0x00, 0x00,
}
