// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v6.32.1
// source: memiavl/changelog.proto

package proto

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	iavl "github.com/cosmos/iavl"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NamedChangeSet combine a tree name with the changeset
type NamedChangeSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changeset *iavl.ChangeSet `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	Name      string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NamedChangeSet) Reset() {
	*x = NamedChangeSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_memiavl_changelog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamedChangeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedChangeSet) ProtoMessage() {}

func (x *NamedChangeSet) ProtoReflect() protoreflect.Message {
	mi := &file_memiavl_changelog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedChangeSet.ProtoReflect.Descriptor instead.
func (*NamedChangeSet) Descriptor() ([]byte, []int) {
	return file_memiavl_changelog_proto_rawDescGZIP(), []int{0}
}

func (x *NamedChangeSet) GetChangeset() *iavl.ChangeSet {
	if x != nil {
		return x.Changeset
	}
	return nil
}

func (x *NamedChangeSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// TreeNameUpgrade defines upgrade of tree names:
// - New tree: { name: "tree" }
// - Delete tree: { name: "tree", delete: true }
// - Rename tree: { name: "new-tree", rename_from: "old-tree" }
type TreeNameUpgrade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RenameFrom string `protobuf:"bytes,2,opt,name=rename_from,json=renameFrom,proto3" json:"rename_from,omitempty"`
	Delete     bool   `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *TreeNameUpgrade) Reset() {
	*x = TreeNameUpgrade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_memiavl_changelog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreeNameUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNameUpgrade) ProtoMessage() {}

func (x *TreeNameUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_memiavl_changelog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNameUpgrade.ProtoReflect.Descriptor instead.
func (*TreeNameUpgrade) Descriptor() ([]byte, []int) {
	return file_memiavl_changelog_proto_rawDescGZIP(), []int{1}
}

func (x *TreeNameUpgrade) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TreeNameUpgrade) GetRenameFrom() string {
	if x != nil {
		return x.RenameFrom
	}
	return ""
}

func (x *TreeNameUpgrade) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

// MultiTreeMetadata stores the metadata for MultiTree
type MultiTreeMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitInfo     *CommitInfo `protobuf:"bytes,1,opt,name=commit_info,json=commitInfo,proto3" json:"commit_info,omitempty"`
	InitialVersion int64       `protobuf:"varint,2,opt,name=initial_version,json=initialVersion,proto3" json:"initial_version,omitempty"`
}

func (x *MultiTreeMetadata) Reset() {
	*x = MultiTreeMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_memiavl_changelog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiTreeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTreeMetadata) ProtoMessage() {}

func (x *MultiTreeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_memiavl_changelog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTreeMetadata.ProtoReflect.Descriptor instead.
func (*MultiTreeMetadata) Descriptor() ([]byte, []int) {
	return file_memiavl_changelog_proto_rawDescGZIP(), []int{2}
}

func (x *MultiTreeMetadata) GetCommitInfo() *CommitInfo {
	if x != nil {
		return x.CommitInfo
	}
	return nil
}

func (x *MultiTreeMetadata) GetInitialVersion() int64 {
	if x != nil {
		return x.InitialVersion
	}
	return 0
}

// ChangelogEntry is a single entry in the changelog
type ChangelogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    int64              `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Changesets []*NamedChangeSet  `protobuf:"bytes,2,rep,name=changesets,proto3" json:"changesets,omitempty"`
	Upgrades   []*TreeNameUpgrade `protobuf:"bytes,3,rep,name=upgrades,proto3" json:"upgrades,omitempty"`
}

func (x *ChangelogEntry) Reset() {
	*x = ChangelogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_memiavl_changelog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangelogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangelogEntry) ProtoMessage() {}

func (x *ChangelogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_memiavl_changelog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangelogEntry.ProtoReflect.Descriptor instead.
func (*ChangelogEntry) Descriptor() ([]byte, []int) {
	return file_memiavl_changelog_proto_rawDescGZIP(), []int{3}
}

func (x *ChangelogEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ChangelogEntry) GetChangesets() []*NamedChangeSet {
	if x != nil {
		return x.Changesets
	}
	return nil
}

func (x *ChangelogEntry) GetUpgrades() []*TreeNameUpgrade {
	if x != nil {
		return x.Upgrades
	}
	return nil
}

var File_memiavl_changelog_proto protoreflect.FileDescriptor

var file_memiavl_changelog_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x65, 0x6d, 0x69, 0x61, 0x76, 0x6c, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x6d, 0x69, 0x61,
	0x76, 0x6c, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x69, 0x61, 0x76, 0x6c, 0x2f, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19,
	0x6d, 0x65, 0x6d, 0x69, 0x61, 0x76, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0e, 0x4e, 0x61, 0x6d,
	0x65, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x74, 0x12, 0x33, 0x0a, 0x09, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x69, 0x61, 0x76, 0x6c, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x74, 0x42,
	0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x0f, 0x54, 0x72, 0x65, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x22, 0x72, 0x0a, 0x11, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x54, 0x72, 0x65,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x0b, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x6d, 0x65, 0x6d, 0x69, 0x61, 0x76, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x99, 0x01, 0x0a, 0x0e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x6c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x6d, 0x69,
	0x61, 0x76, 0x6c, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53,
	0x65, 0x74, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x73, 0x12, 0x34,
	0x0a, 0x08, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6d, 0x65, 0x6d, 0x69, 0x61, 0x76, 0x6c, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x08, 0x75, 0x70, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x69, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x73, 0x65, 0x69, 0x2d, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_memiavl_changelog_proto_rawDescOnce sync.Once
	file_memiavl_changelog_proto_rawDescData = file_memiavl_changelog_proto_rawDesc
)

func file_memiavl_changelog_proto_rawDescGZIP() []byte {
	file_memiavl_changelog_proto_rawDescOnce.Do(func() {
		file_memiavl_changelog_proto_rawDescData = protoimpl.X.CompressGZIP(file_memiavl_changelog_proto_rawDescData)
	})
	return file_memiavl_changelog_proto_rawDescData
}

var file_memiavl_changelog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_memiavl_changelog_proto_goTypes = []interface{}{
	(*NamedChangeSet)(nil),    // 0: memiavl.NamedChangeSet
	(*TreeNameUpgrade)(nil),   // 1: memiavl.TreeNameUpgrade
	(*MultiTreeMetadata)(nil), // 2: memiavl.MultiTreeMetadata
	(*ChangelogEntry)(nil),    // 3: memiavl.ChangelogEntry
	(*iavl.ChangeSet)(nil),    // 4: iavl.ChangeSet
	(*CommitInfo)(nil),        // 5: memiavl.CommitInfo
}
var file_memiavl_changelog_proto_depIdxs = []int32{
	4, // 0: memiavl.NamedChangeSet.changeset:type_name -> iavl.ChangeSet
	5, // 1: memiavl.MultiTreeMetadata.commit_info:type_name -> memiavl.CommitInfo
	0, // 2: memiavl.ChangelogEntry.changesets:type_name -> memiavl.NamedChangeSet
	1, // 3: memiavl.ChangelogEntry.upgrades:type_name -> memiavl.TreeNameUpgrade
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_memiavl_changelog_proto_init() }
func file_memiavl_changelog_proto_init() {
	if File_memiavl_changelog_proto != nil {
		return
	}
	file_memiavl_commit_info_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_memiavl_changelog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamedChangeSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_memiavl_changelog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreeNameUpgrade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_memiavl_changelog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiTreeMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_memiavl_changelog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangelogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_memiavl_changelog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_memiavl_changelog_proto_goTypes,
		DependencyIndexes: file_memiavl_changelog_proto_depIdxs,
		MessageInfos:      file_memiavl_changelog_proto_msgTypes,
	}.Build()
	File_memiavl_changelog_proto = out.File
	file_memiavl_changelog_proto_rawDesc = nil
	file_memiavl_changelog_proto_goTypes = nil
	file_memiavl_changelog_proto_depIdxs = nil
}
